version: '3'
services:
  artbook-app:
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "artbook"
      FLASK_ENV: "development"
      FLASK_DEBUG: 1
      APP_PORT: 5000
    volumes:
      - ./app:/var/www
    depends_on:
      - artbook-db
    networks:
      - artbook-frontend
      - artbook-backend
    command: flask run --host=0.0.0.0

  # disabled services
  artbook-webserver:
    deploy:
      replicas: 0
